theme: jekyll-theme-tactile
url                      : "https://judaihyun.github.io/webpack-docs" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
